server:
  port: 8082
spring:
  #for MySQL Connect
  #useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8mb4;
  datasource:
    url: jdbc:mysql://localhost:3306/myDB?allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user1
    password: user1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  thymeleaf:
    prefix: 'classpath:/templates/'
  web:
    resources:
      static-locations: 'classpath:/static/'